### ISSUE TITLE
Client Disconnected every 5 seconds after connect

### ISSUE THREAD

**Issue by taufiqtab** [dp0ch/Unity-SocketIO-Client#1]
i'm try to implement this plugin using unity 2018.2.7f1
and creating custom index.js server logic

when i connect from the editor, the client disconnect every 5 seconds, then i edit the index.js by adding 
io.set('heartbeat timeout', 4000);
io.set('heartbeat interval', 2000);

and now the unity editor can connect to server and emit some function normaly..

but when i build the game (as windows .exe) and run it, the problem appear again, it's disconnect every 5 second, and can't emit any function to server (since the first connect)

everything work normal in editor (by adding heartbeat in the index.js server as i mention above)

my socket version : 2.1.1 
my node.js version : 8.9.1

**Comment by taufiqtab** [comment]
Problem solved by changing the Api Compatibility Level from .NET 2.0 Subset to .NET 2.0 at build player setting

**Comment by bcjordan** [comment]
Hmm, I'm running in to the same issue but it didn't seem to fix it. Any other steps for this?
